// Supported languages & dialects for the language selector.
// `label` is the human-readable name shown to the user, `value` is a stable
// slug derived from the label (used as the form value).

export interface LanguageOption {
  value: string;
  label: string;
}

export interface LanguageGroup {
  label: string;
  options: LanguageOption[];
}

const slugify = (label: string): string =>
  label
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "") // strip combining diacritics
    .replace(/[()]/g, "")
    .replace(/['ʼ’.]/g, "") // straight/modifier/curly apostrophes
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const toOptions = (labels: string[]): LanguageOption[] =>
  labels.map((label) => ({ value: slugify(label), label }));

const LANGUAGE_LABELS: string[] = [
  "Hindi",
  "Spanish",
  "Russian",
  "French",
  "Turkish",
  "Chinese (simplified)",
  "German",
  "Portuguese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Abkhaz",
  "Acholi",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Angika",
  "Arabic",
  "Armenian",
  "Assamese (Bengali)",
  "Assamese (Latin)",
  "Assyrian Neo-Aramaic",
  "Australian Kriol",
  "Avar",
  "Azerbaijani (Cyrillic)",
  "Azerbaijani (Latin)",
  "Balochi (Southern)",
  "Bambara",
  "Bashkir",
  "Basque",
  "Bassa",
  "Beembe (Kibembe)",
  "Belarusian",
  "Bemba",
  "Bengali",
  "Bhojpuri",
  "Bihari",
  "Bislama",
  "Bodo",
  "Bosnian",
  "Bulgarian",
  "Bulu (Bantu)",
  "Burmese",
  "Cape Verdean Creole",
  "Catalan",
  "Cebuano",
  "Central Alaskan Yupʼik",
  "Central-Eastern Arrernte",
  "Chechen",
  "Chhattisgarhi (Devanagari)",
  "Chhattisgarhi (Odia)",
  "Chichewa",
  "Chinese (Cantonese)",
  "Chinese (Pinyin)",
  "Chinese (traditional)",
  "Chittagonian (Arabic)",
  "Chittagonian (Bengali)",
  "Chittagonian (Latin)",
  "Chokwe",
  "Chuj",
  "Chuukese",
  "Chuvash",
  "Cook Islands Māori",
  "Cornish",
  "Croatian",
  "Czech",
  "Danish",
  "Dholuo",
  "Dhuwal",
  "Dinka",
  "Dogri (Arabic)",
  "Dogri (Devanagari)",
  "Dogri (Dogri)",
  "Dutch",
  "Dyula (Arabic)",
  "Dyula (Latin)",
  "Dyula (N'Ko)",
  "Dzongkha",
  "Eastern Kayah",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Falam Chin",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "Fon",
  "Frisian",
  "Fula",
  "Ga",
  "Galician",
  "Ganda",
  "Garo (Bengali)",
  "Garo (Latin)",
  "Georgian",
  "Gilbertese",
  "Greek",
  "Greenlandic",
  "Guarani",
  "Gujarati",
  "Gusii (Arabic)",
  "Gusii (Latin)",
  "Haitian Creole",
  "Hakha Chin",
  "Hausa (Latin)",
  "Hawaiian",
  "Hazaragi",
  "Hebrew",
  "Herero",
  "Hiligaynon",
  "Hindi (Devanagari)",
  "Hindi (Latin)",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Ikwere",
  "Ilocano",
  "Indonesian",
  "Ingush",
  "Irish",
  "Italian",
  "Iu Mien",
  "Javanese",
  "Jola",
  "Juba Arabic (Latin)",
  "Kabardian",
  "Kabyle",
  "Kanauji",
  "Kannada",
  "Kaonde",
  "Kapampangan",
  "Karen",
  "Kashmiri (Arabic)",
  "Kashmiri (Devanagari)",
  "Kazakh",
  "Khasi",
  "Khmer",
  "Kiga",
  "Kikuyu",
  "Kimbundu",
  "Kinyarwanda",
  "Kirundi",
  "Komi",
  "Konkani (Devanagari)",
  "Konkani (Latin)",
  "Konzo",
  "Krio",
  "Kurdish (Kurmandji)",
  "Kurdish (Palewani)",
  "Kurdish (Sorani)",
  "Kwanyama",
  "Kyrgyz",
  "Kʼicheʼ",
  "Lamba",
  "Lango",
  "Lao",
  "Latin",
  "Latvian",
  "Lenje",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Lozi",
  "Luba-Kasai",
  "Luchazi",
  "Luhya",
  "Lunda",
  "Luvale",
  "Luxembourgish",
  "Maasai",
  "Maca",
  "Macedonian",
  "Madurese (Arabic)",
  "Madurese (Javanese)",
  "Madurese (Latin)",
  "Magahi",
  "Maithili",
  "Makhuwa",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Mam",
  "Mandinka (Arabic)",
  "Mandinka (Latin)",
  "Mandinka (N'Ko)",
  "Maori",
  "Marathi",
  "Mari",
  "Marshallese",
  "Meitei (Bengali)",
  "Meitei (Latin)",
  "Meitei (Meitei)",
  "Mizo",
  "Mongolian",
  "Montenegrin",
  "Mooré (Latin)",
  "Mooré (N'Ko)",
  "Nagpuri",
  "Navaho",
  "Ndonga",
  "Nepali",
  "Nigerian Pidgin",
  "Niuean",
  "Nkore",
  "Northern Ndebele",
  "Northern Sotho",
  "Norwegian",
  "Nuer",
  "Nyoro",
  "Occitan",
  "Odia",
  "Oromo",
  "Ossetian",
  "Papiamento",
  "Pashto",
  "Persian",
  "Pijin",
  "Pitjantjatjara",
  "Pohnpeian",
  "Polish",
  "Pulaar (Adlam)",
  "Pulaar (Arabic)",
  "Pulaar (Latin)",
  "Punjabi (Gurmukhi)",
  "Punjabi (Shahmukhi)",
  "Qʼeqchiʼ",
  "Rangi",
  "Rohingya (Hanifi)",
  "Rohingya (Latin)",
  "Romanian",
  "Rongmei (Latin)",
  "Rongmei (Meitei)",
  "S'gaw Karen (Burmese)",
  "S'gaw Karen (Latin)",
  "Sakha",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Santali (Bengali)",
  "Santali (Latin)",
  "Santali (Odia)",
  "Santali (Ol Chiki)",
  "Saraiki",
  "Sardinian",
  "Scottish Gaelic",
  "Serbian (Cyrillic)",
  "Serbian (Latin)",
  "Serer",
  "Sesotho",
  "Shan",
  "Shona",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovenian",
  "Somali",
  "Soninke",
  "Southern Ndebele",
  "Sundanese",
  "Susu",
  "Swahili",
  "Swati",
  "Swedish",
  "Tachelhit (Shilha) (Arabic)",
  "Tachelhit (Shilha) (Latin)",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Tedim Chin",
  "Telugu",
  "Tetum",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tiwi",
  "Tonga",
  "Tongan",
  "Tooro",
  "Torres Strait Creole",
  "Tsonga",
  "Tswana",
  "Turkmen",
  "Twi",
  "Udmurt",
  "Ukrainian",
  "Urdu (Arabic)",
  "Urdu (Latin)",
  "Uyghur",
  "Uzbek (Cyrillic)",
  "Uzbek (Latin)",
  "Venda",
  "Vlax Romani (Cyrillic)",
  "Vlax Romani (Latin)",
  "Waray",
  "Warlpiri",
  "Welsh",
  "Western Arrernte",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

const DIALECT_LABELS: string[] = [
  "Arabic (Algeria)",
  "Arabic (Bahrain)",
  "Arabic (Egypt)",
  "Arabic (Iraq)",
  "Arabic (Israel)",
  "Arabic (Jordan)",
  "Arabic (Kuwait)",
  "Arabic (Lebanon)",
  "Arabic (Morocco)",
  "Arabic (Qatar)",
  "Arabic (Saudi Arabia)",
  "Arabic (Sudan)",
  "Arabic (UAE)",
  "Armenian (Eastern)",
  "Armenian (Western)",
  "Chinese (simplified, Malaysia)",
  "Chinese (simplified, PRC)",
  "Chinese (simplified, Singapore)",
  "Chinese (traditional, Hong Kong)",
  "Chinese (traditional, Macau)",
  "Chinese (traditional, Taiwan)",
  "Dutch (Aruba)",
  "Dutch (Belgium)",
  "Dutch (Bonaire, Sint Eustatius and Saba)",
  "Dutch (Curaçao)",
  "Dutch (Netherlands)",
  "Dutch (Sint Maarten)",
  "Dutch (Suriname)",
  "English (Australia)",
  "English (Canada)",
  "English (India)",
  "English (Ireland)",
  "English (New Zealand)",
  "English (Philippines)",
  "English (Singapore)",
  "English (South Africa)",
  "English (USA)",
  "English (United Kingdom)",
  "French (Belgium)",
  "French (Cameroon)",
  "French (Canada)",
  "French (France)",
  "French (Ghana)",
  "French (Ivory Coast)",
  "French (Senegal)",
  "French (Switzerland)",
  "German (Austria)",
  "German (Germany)",
  "German (Switzerland)",
  "Italian (Italy)",
  "Italian (Switzerland)",
  "Malay (Malaysia)",
  "Malay (Singapore)",
  "Norwegian (Bokmål)",
  "Norwegian (Nynorsk)",
  "Papiamento (Aruba)",
  "Papiamentu (Bonaire, Sint Eustatius and Saba)",
  "Papiamentu (Curaçao)",
  "Persian (Afghanistan) / Dari",
  "Persian (Iran)",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Romanian (Moldova)",
  "Romanian (Romania)",
  "Russian (Belarus)",
  "Russian (Kazakhstan)",
  "Russian (Russia)",
  "Spanish (Argentina)",
  "Spanish (Chile)",
  "Spanish (Colombia)",
  "Spanish (Guatemala)",
  "Spanish (Latin America)",
  "Spanish (Mexico)",
  "Spanish (Nicaragua)",
  "Spanish (Peru)",
  "Spanish (Puerto Rico)",
  "Spanish (Spain)",
  "Spanish (USA)",
  "Tamil (India)",
  "Tamil (Malaysia)",
  "Tamil (Singapore)",
  "Tamil (Sri Lanka)",
  "Urdu (Arabic, India)",
  "Urdu (Arabic, Pakistan)",
];

export const languageGroups: LanguageGroup[] = [
  { label: "Languages", options: toOptions(LANGUAGE_LABELS) },
  { label: "Dialects", options: toOptions(DIALECT_LABELS) },
];

/** Flat list of every language/dialect option. */
export const languages: LanguageOption[] = languageGroups.flatMap(
  (group) => group.options,
);

/** Look up a single option by its slug value. */
export const getLanguageByValue = (value: string): LanguageOption | undefined =>
  languages.find((l) => l.value === value);
